"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";

type User={full_name?:string;name?:string;username?:string;email?:string;role?:string;avatar_url?:string};
export default function Header(){
 const router=useRouter(),menuRef=useRef<HTMLDivElement>(null);
 const [mobileOpen,setMobileOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[user,setUser]=useState<User|null>(null),[sharedStaff,setSharedStaff]=useState(false),[unread,setUnread]=useState(0);
 useEffect(()=>{const refresh=()=>api<{user:User;shared_staff_session?:boolean}>("/auth/me").then(r=>{setUser(r.user);setSharedStaff(Boolean(r.shared_staff_session));return api<{count:number}>("/operations/notifications/unread-count")}).then(r=>setUnread(r.count)).catch(()=>{setUser(null);setSharedStaff(false);setUnread(0)});const outside=(e:MouseEvent)=>{if(menuRef.current&&!menuRef.current.contains(e.target as Node))setAccountOpen(false)};refresh();window.addEventListener("novatech-auth-changed",refresh);document.addEventListener("mousedown",outside);return()=>{window.removeEventListener("novatech-auth-changed",refresh);document.removeEventListener("mousedown",outside)}},[]);
 const displayName=user?.full_name||user?.name||user?.username||user?.email||"Account",initials=displayName.split(" ").map(p=>p[0]).join("").slice(0,2).toUpperCase(),isPortalUser=user?.role==="candidate"||user?.role==="employee",destination=isPortalUser?"/portal":"/dashboard";
 async function logout(){try{await api("/auth/logout",{method:"POST"})}finally{setUser(null);setSharedStaff(false);setAccountOpen(false);window.dispatchEvent(new Event("novatech-auth-changed"));router.push("/")}}
 return <header className="site-header"><div className="container nav-wrap"><Link className="brand" href="/"><span className="brand-mark">N</span><span>NovaTech <b>Solutions</b></span></Link><button className="menu" aria-label="Toggle navigation" onClick={()=>setMobileOpen(!mobileOpen)}>☰</button><nav className={mobileOpen?"nav open":"nav"}>{!user&&<><Link href="/">Home</Link><Link href="/jobs">Open roles</Link><Link href="/company">Company</Link><Link href="/login">Team login</Link><Link className="button small" href="/jobs">Find your role</Link></>}{user&&<><Link href={destination}>{isPortalUser?"My portal":"Dashboard"}</Link><Link href="/notifications" aria-label={`Notifications${unread?`, ${unread} unread`:""}`}>Notifications{unread?` (${unread})`:""}</Link><div className="account-menu" ref={menuRef}><button className="account-trigger" onClick={()=>setAccountOpen(!accountOpen)} aria-expanded={accountOpen}>{user.avatar_url?<img className="account-avatar" src={user.avatar_url} alt=""/>:<span className="account-initials">{initials}</span>}<span className="account-name">{displayName}</span></button>{accountOpen&&<div className="account-dropdown"><Link href={destination}>{isPortalUser?"My portal":"Dashboard"}</Link>{sharedStaff&&<Link href="/staff-select">Switch staff profile</Link>}<Link href="/account">Account settings</Link><button onClick={logout}>Sign out</button></div>}</div></>}</nav></div></header>;
}
