"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { API_URL, api } from "@/lib/api";

type App = { id: string; name_at_application: string; status: string; final_score?: number; job_positions?: { title: string } };
export default function Operations() {
  const [apps, setApps] = useState<App[]>([]); const [analytics, setAnalytics] = useState<any>({}); const [health, setHealth] = useState<any>({ executions: [], errors: [] }); const [notifications, setNotifications] = useState<any[]>([]); const [error, setError] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  function load() { const filter = dateFrom || dateTo ? `?${dateFrom ? `date_from=${dateFrom}` : ""}${dateFrom && dateTo ? "&" : ""}${dateTo ? `date_to=${dateTo}` : ""}` : ""; Promise.all([api<{ items: App[] }>("/operations/pipeline"), api<{ metrics: any }>(`/operations/analytics${filter}`), api<any>("/operations/workflow-health"), api<{ items: any[] }>("/operations/notifications")]).then(([pipeline, report, workflow, notice]) => { setApps(pipeline.items); setAnalytics(report.metrics); setHealth(workflow); setNotifications(notice.items); }).catch(err => setError(err.message)); }
  useEffect(() => { load(); }, []);
  async function move(id: string, status: string) { const previous=apps; setApps(items=>items.map(item=>item.id===id?{...item,status}:item)); try { await api(`/operations/applications/${id}/stage`, { method: "PATCH", body: JSON.stringify({ status, reason: "Updated from recruitment pipeline" }) }); setError(""); } catch (err) { setApps(previous); setError(err instanceof Error ? err.message : "Update failed"); } }
  const query = dateFrom || dateTo ? `?${dateFrom ? `date_from=${dateFrom}` : ""}${dateFrom && dateTo ? "&" : ""}${dateTo ? `date_to=${dateTo}` : ""}` : "";
  const exportUrl = `${API_URL}/operations/analytics/export${query}`;
  const reportUrl = `${API_URL}/operations/analytics/report.pdf${query}`;
  return <div className="resource-page"><div className="container section"><Link className="back" href="/dashboard">← Dashboard</Link><span className="eyebrow">Control centre</span><h1>Recruitment operations</h1>{error && <div className="notice error">{error}</div>}<section className="form-card"><div className="table-head"><div><h2>Analytics window</h2><p className="muted">Filter server-side aggregates before exporting.</p></div><a className="button small" href={exportUrl}>Export CSV</a></div><div className="filters"><label>From<input type="date" value={dateFrom} onChange={event => setDateFrom(event.target.value)} /></label><label>To<input type="date" value={dateTo} onChange={event => setDateTo(event.target.value)} /></label><button className="button" onClick={load}>Apply filters</button></div></section><div className="metric-cards"><article><span>Applications</span><b>{analytics.applications_total || 0}</b></article><article><span>Interviews</span><b>{analytics.interviews_total || 0}</b></article><article><span>Offers</span><b>{analytics.offers_total || 0}</b></article></div><div className="detail-grid"><section className="table-card"><h2>Pipeline</h2><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Role</th><th>Score</th><th>Stage</th></tr></thead><tbody>{apps.map(application => <tr key={application.id}><td><b>{application.name_at_application}</b></td><td>{application.job_positions?.title}</td><td>{application.final_score ?? "—"}</td><td><select value={application.status} onChange={event => move(application.id, event.target.value)}><option>NEW</option><option>MANUAL_REVIEW</option><option>SHORTLISTED</option><option>INTERVIEW_SCHEDULED</option><option>INTERVIEWED</option><option>SELECTED</option><option>OFFERED</option><option>ACCEPTED</option><option>REJECTED</option><option>ONBOARDING</option><option>ONBOARDED</option></select></td></tr>)}</tbody></table></div></section><aside><section className="form-card"><h2>Automation health</h2><p><b>{health.errors?.length || 0}</b> open/retrying/dead errors</p><p><b>{health.executions?.length || 0}</b> recent executions loaded</p></section><section className="form-card"><h2>Notifications</h2>{notifications.slice(0, 8).map(notification => <article key={notification.id}><b>{notification.title}</b><p>{notification.message}</p><small>{new Date(notification.created_at).toLocaleString()}</small></article>)}{!notifications.length && <p className="muted">No notifications.</p>}</section></aside></div></div></div>;
}
