"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

type Application = { id: string; application_code: string; name_at_application: string; email_at_application: string; experience_years: number; status: string; final_score?: number; created_at: string; job_positions?: { title: string; department: string } };
export default function Applications() {
  const [items, setItems] = useState<Application[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [hasMore, setHasMore] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { const params = new URLSearchParams({ page: String(page), page_size: "50" }); if (query) params.set("search", query); if (status) params.set("status", status); const result = await api<{ items: Application[]; has_more: boolean }>(`/admin/applications?${params}`); setItems(result.items); setHasMore(result.has_more); setSelected([]); } catch (err) { setError(err instanceof Error ? err.message : "Applications could not load"); } }
  useEffect(() => { load(); }, [page, status]);
  async function bulk(action: "SHORTLIST" | "REJECT" | "ARCHIVE") { if (!selected.length || !window.confirm(`Confirm ${action.toLowerCase()} for ${selected.length} applications?`)) return; try { const result = await api<{ message: string }>("/operations/applications/bulk", { method: "POST", body: JSON.stringify({ application_ids: selected, action, confirm: true }) }); setMessage(result.message); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Bulk action failed"); } }
  return <div className="resource-page"><div className="container section"><Link className="back" href="/dashboard">← Dashboard</Link><span className="eyebrow">Recruitment pipeline</span><h1>Applications</h1><div className="filters"><input placeholder="Search candidate, code or email" value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => event.key === "Enter" && load()} /><select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option><option>MANUAL_REVIEW</option><option>SHORTLISTED</option><option>INTERVIEW_SCHEDULED</option><option>REJECTED</option><option>SELECTED</option></select><button className="button" onClick={() => { setPage(1); load(); }}>Search</button></div>{selected.length > 0 && <div className="actions"><button className="button small" onClick={() => bulk("SHORTLIST")}>Shortlist</button><button className="button small ghost" onClick={() => bulk("REJECT")}>Reject</button><button className="button small ghost" onClick={() => bulk("ARCHIVE")}>Archive</button></div>}{message && <div className="notice success">{message}</div>}{error && <div className="notice error">{error}</div>}<section className="table-card"><div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Select all visible applications" checked={items.length > 0 && selected.length === items.length} onChange={event => setSelected(event.target.checked ? items.map(item => item.id) : [])} /></th><th>Candidate</th><th>Position</th><th>Status</th><th>Score</th><th>Submitted</th><th></th></tr></thead><tbody>{items.map(application => <tr key={application.id}><td><input type="checkbox" aria-label={`Select ${application.name_at_application}`} checked={selected.includes(application.id)} onChange={event => setSelected(current => event.target.checked ? [...current, application.id] : current.filter(id => id !== application.id))} /></td><td><b>{application.name_at_application}</b><small>{application.email_at_application}</small></td><td>{application.job_positions?.title}<small>{application.job_positions?.department}</small></td><td><span className="status">{application.status}</span></td><td>{application.final_score ?? "—"}</td><td>{new Date(application.created_at).toLocaleDateString()}</td><td><Link className="arrow-link" href={`/dashboard/applications/${application.id}`}>View details →</Link></td></tr>)}</tbody></table></div>{!items.length && <div className="notice">No matching applications.</div>}<div className="actions"><button className="button small ghost" disabled={page <= 1} onClick={() => setPage(current => current - 1)}>Previous</button><span>Page {page}</span><button className="button small ghost" disabled={!hasMore} onClick={() => setPage(current => current + 1)}>Next</button></div></section></div></div>;
}
