"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";

type Interviewer = { id:string; full_name:string; role:string; department?:string; job_title?:string };
export default function ApplicationDetail() {
  const { id } = useParams<{id:string}>();
  const [data,setData]=useState<any>(null),[interviewers,setInterviewers]=useState<Interviewer[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
  async function load(){try{const detail=await api<any>(`/admin/applications/${id}`);setData(detail);setError("");api<{items:Interviewer[]}>("/admin/interviewers").then(people=>setInterviewers(people.items)).catch(()=>setInterviewers([]));}catch(reason){setError(reason instanceof Error?reason.message:"Candidate could not load");}}
  useEffect(()=>{load();},[id]);
  async function action(label:string,task:()=>Promise<any>){setBusy(label);setError("");setMessage("");try{const result=await task();setMessage(result.message||"Saved");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Action failed");}finally{setBusy("");}}
  async function move(status:string){await action(status,()=>api(`/operations/applications/${id}/stage`,{method:"PATCH",body:JSON.stringify({status,reason:"Updated from candidate review"})}));}
  async function note(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);await action("note",()=>api(`/admin/applications/${id}/notes`,{method:"POST",body:JSON.stringify({note:values.get("note"),visibility:values.get("visibility")})}));form.reset();}
  async function openCv(download=false){try{const result=await api<{url:string;filename:string}>(`/admin/applications/${id}/cv`);const link=document.createElement("a");link.href=result.url;link.target="_blank";link.rel="noopener noreferrer";if(download)link.download=result.filename||"candidate-cv";link.click();}catch(reason){setError(reason instanceof Error?reason.message:"CV is unavailable");}}
  async function assign(event:FormEvent<HTMLFormElement>,interviewId:string){event.preventDefault();const values=new FormData(event.currentTarget);await action("assign",()=>api(`/admin/interviews/${interviewId}/assignment`,{method:"PATCH",body:JSON.stringify({interviewer_id:values.get("interviewer_id"),approve:true,assignment_role:"LEAD",interview_type:values.get("interview_type"),round_number:1,duration_minutes:60})}));}
  async function hiringDecision(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);await action("decision",()=>api(`/admin/applications/${id}/hiring-decision`,{method:"POST",body:JSON.stringify({action:values.get("action"),reason:values.get("reason")})}));}
  if(!data)return <div className="container section"><div className="notice">Loading candidate…</div>{error&&<div className="notice error">{error}</div>}</div>;
  const application=data.item,review=application.ai_review||{},interview=application.interviews?.[0],assignment=interview?.interview_assignments?.find((value:any)=>["PENDING_APPROVAL","APPROVED","ACCEPTED"].includes(value.status))||interview?.interview_assignments?.[0];
  const jobDepartment=String(application.job_positions?.department||"").trim().toLowerCase();
  const eligibleInterviewers=interviewers.filter(person=>person.role==="hr"||(["interviewer","hiring_manager"].includes(person.role)&&String(person.department||"").trim().toLowerCase()===jobDepartment));
  return <div className="resource-page"><div className="container section">
    <Link className="back" href="/dashboard/applications">← Applications</Link><span className="eyebrow">{application.application_code}</span><h1>{application.name_at_application}</h1>
    {message&&<div className="notice success">{message}</div>}{error&&<div className="notice error">{error}</div>}
    <div className="metric-cards"><article><span>Status</span><b>{application.status}</b></article><article><span>CV score</span><b>{application.final_score??"—"}</b></article><article><span>CV experience</span><b>{review.cv_experience_years??application.experience_years??"—"} years</b></article></div>
    <section className="form-card"><div className="table-head"><div><h2>Review actions</h2><p className="muted">Clean CV evidence scoring 80+ is shortlisted; all lower, suspicious or mismatched results remain in manual review.</p></div><button className="button" disabled={!!busy} onClick={()=>action("review",()=>api(`/admin/applications/${id}/review`,{method:"POST"}))}>{busy==="review"?"Reviewing CV…":"Run / re-run CV review"}</button></div><div className="button-row"><button className="button small" onClick={()=>move("SHORTLISTED")}>Shortlist</button><button className="button small secondary" onClick={()=>move("MANUAL_REVIEW")}>Manual review</button><button className="button small danger" onClick={()=>move("REJECTED")}>Reject</button></div></section>
    <div className="detail-grid"><section className="table-card"><h2>Candidate details</h2><dl className="profile-grid">
      <div><dt>Email</dt><dd>{application.email_at_application}</dd></div><div><dt>Phone</dt><dd>{application.phone_at_application}</dd></div><div><dt>Position</dt><dd>{application.job_positions?.title}</dd></div><div><dt>Expected salary</dt><dd>{application.currency} {application.expected_salary}</dd></div><div><dt>Form skills</dt><dd>{Array.isArray(application.skills)?application.skills.join(", "):"—"}</dd></div>
      <div><dt>CV</dt><dd>{application.cv_storage_path?<><button className="text-link" onClick={()=>openCv()}>View</button> · <button className="text-link" onClick={()=>openCv(true)}>Download</button></>:"Not provided"}</dd></div><div><dt>CV security</dt><dd><span className="status">{application.cv_security_status||"NOT_SCANNED"}</span></dd></div>
    </dl><h2>CV evidence review</h2><p>{review.candidate_summary||"Run CV review to generate an evidence-based summary."}</p><p><b>Recommendation:</b> {review.ai_recommendation||"—"}</p>
    {!!review.verified_skills?.length&&<p><b>Verified:</b> {review.verified_skills.join(", ")}</p>}{!!review.missing_requirements?.length&&<p><b>Missing:</b> {review.missing_requirements.join(", ")}</p>}{!!review.form_mismatches?.length&&<div className="notice error"><b>Form/CV mismatch</b>{review.form_mismatches.map((value:string)=><p key={value}>{value}</p>)}</div>}
    {!!review.score_breakdown?.length&&<div className="table-scroll"><table><thead><tr><th>Criterion</th><th>Points</th><th>Evidence</th></tr></thead><tbody>{review.score_breakdown.map((item:any)=><tr key={item.criterion}><td>{item.criterion}</td><td>{item.points}/{item.maximum}</td><td>{item.evidence}</td></tr>)}</tbody></table></div>}
    <h2>Activity timeline</h2>{data.history.map((item:any)=><div className="timeline-item" key={item.id}><b>{item.new_status}</b><span>{new Date(item.changed_at).toLocaleString()}</span><p>{item.reason}</p></div>)}</section>
    <aside>{data.scorecards?.length>0&&<form className="form-card" onSubmit={hiringDecision}><h2>Hiring decision</h2><p className="muted">Interview evidence is complete. Hiring Manager and HR approvals are tracked separately.</p>{data.scorecards.map((card:any)=><div className="notice" key={card.id}><b>{card.overall_score}/10 · {String(card.recommendation).replaceAll("_"," ")}</b><br/><small>{card.user_profiles?.full_name||"Interviewer"}</small><p>{card.comments||"No comments provided."}</p></div>)}<p>Status: <span className="status">{data.hiring_decision?.status||"PENDING"}</span></p><label>Decision<select name="action"><option value="APPROVE">Approve</option><option value="SECOND_INTERVIEW">Second interview</option><option value="RETURN_TO_REVIEW">Return to review</option><option value="REJECT">Reject</option></select></label><label>Reason<textarea name="reason" rows={4} minLength={3} required/></label><button className="button full" disabled={busy==="decision"}>{busy==="decision"?"Saving…":"Record decision"}</button></form>}<section className="form-card"><h2>Interview</h2>{!interview?<><p>No interview exists yet.</p><button className="button full" onClick={()=>action("interview",()=>api(`/admin/applications/${id}/interview`,{method:"POST"}))}>Create & auto-suggest interviewer</button></>:<><p><b>{interview.interview_code}</b></p><p>Status: {interview.status}<br/>Approval: {interview.assignment_status}</p>{assignment?.user_profiles&&<div className="notice"><b>Suggested:</b> {assignment.user_profiles.full_name}<br/><small>{assignment.user_profiles.job_title||assignment.user_profiles.role}</small></div>}<form onSubmit={event=>assign(event,interview.id)}><label>Eligible interviewer<select name="interviewer_id" defaultValue={interview.interviewer_id||""} required><option value="">Select department staff or HR</option>{eligibleInterviewers.map(person=><option value={person.id} key={person.id}>{person.full_name} — {person.department||person.role}</option>)}</select></label><p className="muted">Administrators are excluded. Priority is the job department’s interviewer, then its hiring manager, with HR as fallback.</p><label>Interview type<select name="interview_type" defaultValue={interview.interview_type||"Technical"}><option>Screening</option><option>Technical</option><option>HR</option><option>Managerial</option><option>Final</option></select></label><p className="muted">After approval, the assigned interviewer selects the exact date and time from their workspace. The system then creates the Google Meet.</p><button className="button full" disabled={busy==="assign"}>{busy==="assign"?"Saving…":"Approve / change assignment"}</button></form></>}</section>
    <form className="form-card" onSubmit={note}><h2>Add internal note</h2><label>Visibility<select name="visibility"><option value="HIRING_TEAM">Hiring team</option><option value="HR_ONLY">HR only</option><option value="ADMIN_ONLY">Admin only</option></select></label><label>Note<textarea name="note" rows={5} required/></label><button className="button">Add note</button></form><div className="form-card notes-card"><h2>Notes</h2>{data.notes.map((item:any)=><article key={item.id}><span className="tag">{item.visibility}</span><p>{item.note}</p><small>{new Date(item.created_at).toLocaleString()}</small></article>)}</div></aside></div>
  </div></div>;
}
