"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

export default function CandidateRegister(){
  const [email,setEmail]=useState(""),[ready,setReady]=useState(false),[step,setStep]=useState(1),[token,setToken]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{setEmail(new URLSearchParams(window.location.search).get("email")||"");setReady(true);},[]);
  async function send(){setBusy(true);setError("");try{const result=await api<{message:string}>("/auth/otp/request",{method:"POST",body:JSON.stringify({identifier:email,purpose:"CANDIDATE_REGISTRATION"})});setMessage(result.message);setStep(2);}catch(reason){setError(reason instanceof Error?reason.message:"Code could not be sent");}finally{setBusy(false);}}
  async function verify(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);try{const result=await api<{data:{verification_token:string}}>("/auth/otp/verify",{method:"POST",body:JSON.stringify({identifier:email,purpose:"CANDIDATE_REGISTRATION",otp:data.get("otp")})});setToken(result.data.verification_token);setStep(3);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Code is invalid");}finally{setBusy(false);}}
  async function complete(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),password=String(data.get("password")),confirm=String(data.get("confirm"));if(password!==confirm){setError("Passwords do not match");return;}setBusy(true);try{await api("/auth/password/complete?purpose=CANDIDATE_REGISTRATION",{method:"POST",body:JSON.stringify({verification_token:token,username:data.get("username"),password})});setStep(4);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Account could not be created");}finally{setBusy(false);}}
  return <div className="auth-page"><div className="auth-card"><span className="eyebrow">Candidate account</span><h1>Create your secure portal</h1>{!ready?<div className="notice">Loading secure invitation…</div>:<><p>Your application email is <b>{email||"missing"}</b>.</p>{!email&&<div className="notice error">Open the registration link sent to your application email.</div>}{step===1&&email&&<button className="button full" disabled={busy} onClick={send}>{busy?"Sending…":"Send verification code"}</button>}{step===2&&<form onSubmit={verify}><p>{message}</p><label>Six-digit code<input name="otp" inputMode="numeric" pattern="[0-9]{6}" required/></label><button className="button full" disabled={busy}>Verify email</button></form>}{step===3&&<form onSubmit={complete}><label>Choose username<input name="username" minLength={3} pattern="[a-zA-Z0-9._-]+" required/></label><label>Choose password<input name="password" type="password" minLength={10} required/></label><label>Confirm password<input name="confirm" type="password" minLength={10} required/></label><button className="button full" disabled={busy}>Create account</button></form>}{step===4&&<><div className="notice success">Your candidate account is ready.</div><Link className="button full" href="/login">Sign in</Link></>}{error&&<div className="notice error">{error}</div>}</>}</div></div>;
}
