"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
type Decision={id:string;status:string;manager_status:string;hr_status:string;applications:any};
export default function HiringDecisionsPage(){
 const [items,setItems]=useState<Decision[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[filter,setFilter]=useState("OPEN"),[selected,setSelected]=useState<Decision|null>(null),[busy,setBusy]=useState(false);
 async function load(){try{const result=await api<{items:Decision[]}>("/admin/hiring-decisions");setItems(result.items);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Hiring decisions could not load");}}
 useEffect(()=>{load();},[]);
 const shown=useMemo(()=>items.filter(item=>filter==="ALL"||(filter==="OPEN"?!["APPROVED","REJECTED"].includes(item.status):item.status===filter)),[items,filter]);
 async function decide(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);setBusy(true);setError("");try{const result=await api<{message:string}>(`/admin/applications/${selected.applications.id}/hiring-decision`,{method:"POST",body:JSON.stringify({action:data.get("action"),reason:data.get("reason")})});setMessage(result.message);setSelected(null);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Decision could not be saved");}finally{setBusy(false);}}
 return <div className="resource-page"><div className="container section"><Link className="back" href="/dashboard">← Dashboard</Link><span className="eyebrow">Human approval</span><h1>Hiring decisions</h1><p className="muted">Review interview evidence before approving an offer. Hiring Manager and HR approvals are recorded separately; Admin can make a final audited decision.</p>{message&&<div className="notice success">{message}</div>}{error&&<div className="notice error">{error}</div>}<div className="button-row">{["OPEN","PENDING_MANAGER","PENDING_HR","APPROVED","REJECTED","ALL"].map(value=><button key={value} className={`button small ${filter===value?"":"ghost"}`} onClick={()=>setFilter(value)}>{value.replaceAll("_"," ")}</button>)}</div><section className="table-card"><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Position</th><th>Interview evidence</th><th>Manager</th><th>HR</th><th>Status</th><th>Action</th></tr></thead><tbody>{shown.map(item=>{const app=item.applications||{},scorecards=(app.interviews||[]).flatMap((interview:any)=>interview.interview_scorecards||[]),latest=scorecards[0];return <tr key={item.id}><td><b>{app.name_at_application}</b><small>{app.application_code}</small></td><td>{app.job_positions?.title}<small>{app.job_positions?.department}</small></td><td>{latest?<><b>{latest.overall_score}/10 · {String(latest.recommendation).replaceAll("_"," ")}</b><small>{latest.user_profiles?.full_name||"Interviewer"} — {latest.comments||"No comments"}</small></>:<span className="muted">No scorecard</span>}</td><td><span className="status">{item.manager_status}</span></td><td><span className="status">{item.hr_status}</span></td><td><span className="status">{item.status}</span></td><td><Link className="button small ghost" href={`/dashboard/applications/${app.id}`}>Full profile</Link> {!['APPROVED','REJECTED'].includes(item.status)&&<button className="button small" onClick={()=>setSelected(item)}>Decide</button>}</td></tr>})}</tbody></table></div>{!shown.length&&<div className="notice">No candidates match this queue.</div>}</section>{selected&&<div className="modal-backdrop"><form className="form-card modal-card" onSubmit={decide}><div className="table-head"><h2>Record hiring decision</h2><button type="button" className="icon-button" onClick={()=>setSelected(null)}>×</button></div><p><b>{selected.applications?.name_at_application}</b> — {selected.applications?.job_positions?.title}</p><label>Decision<select name="action" required><option value="APPROVE">Approve</option><option value="SECOND_INTERVIEW">Request second interview</option><option value="RETURN_TO_REVIEW">Return to manual review</option><option value="REJECT">Reject</option></select></label><label>Decision reason<textarea name="reason" minLength={3} maxLength={3000} rows={5} required/></label><button className="button full" disabled={busy}>{busy?"Saving…":"Save decision"}</button></form></div>}</div></div>;
}
