"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

type Employee = { id: string; employee_code: string; department: string; start_date: string; status: string; candidates?: { full_name: string; email: string } };
type Task = { id: string; title: string; due_date: string; status: string };

export default function EmployeesPage() {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [selected, setSelected] = useState<{ employee: Employee; tasks: Task[]; progress_percent: number } | null>(null);
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { const result = await api<{ items: Employee[] }>("/admin/employees"); setEmployees(result.items); } catch (err) { setError(err instanceof Error ? err.message : "Employees could not load"); } }
  useEffect(() => { load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { const result = await api<{ message: string }>("/admin/employees", { method: "POST", body: JSON.stringify({ offer_id: data.get("offer_id"), employee_code: data.get("employee_code"), department: data.get("department"), start_date: data.get("start_date") }) }); setMessage(result.message); event.currentTarget.reset(); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Employee could not be created"); } finally { setBusy(false); } }
  async function inspect(employee: Employee) { try { setSelected(await api<{ employee: Employee; tasks: Task[]; progress_percent: number }>(`/admin/employees/${employee.id}/onboarding`)); } catch (err) { setError(err instanceof Error ? err.message : "Onboarding could not load"); } }
  async function updateTask(task: Task, status: string) { try { await api(`/admin/onboarding/tasks/${task.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); if (selected) await inspect(selected.employee); } catch (err) { setError(err instanceof Error ? err.message : "Task update failed"); } }
  return <div className="resource-page"><div className="container section"><Link className="back" href="/dashboard">← Dashboard</Link><span className="eyebrow">People operations</span><h1>Employees & onboarding</h1>{message && <div className="notice success">{message}</div>}{error && <div className="notice error">{error}</div>}<div className="detail-grid"><section className="table-card"><h2>Employees</h2><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Department</th><th>Start date</th><th>Status</th><th>Action</th></tr></thead><tbody>{employees.map(employee => <tr key={employee.id}><td><b>{employee.employee_code}</b><small>{employee.candidates?.full_name}</small></td><td>{employee.department}</td><td>{employee.start_date}</td><td><span className="status">{employee.status}</span></td><td><button className="button small" onClick={() => inspect(employee)}>Onboarding</button></td></tr>)}</tbody></table></div>{!employees.length && <div className="notice">No employees available.</div>}</section><form className="form-card" onSubmit={create}><h2>Create employee</h2><label>Accepted offer ID<input name="offer_id" required placeholder="UUID" /></label><label>Employee code<input name="employee_code" required pattern="[A-Za-z0-9_-]+" /></label><label>Department<input name="department" required /></label><label>Start date<input name="start_date" type="date" required /></label><button className="button full" disabled={busy}>{busy ? "Creating..." : "Create employee"}</button></form></div>{selected && <section className="table-card"><div className="table-head"><div><span className="eyebrow">Onboarding progress</span><h2>{selected.employee.employee_code}</h2></div><b>{selected.progress_percent}%</b></div>{selected.tasks.map(task => <div className="notice" key={task.id}><b>{task.title}</b><p>Due {task.due_date}</p><span className="status">{task.status}</span>{task.status !== "COMPLETED" && <button className="button small" onClick={() => updateTask(task, "COMPLETED")}>Complete</button>}</div>)}</section>}</div></div>;
}
