"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

type Requisition = { id: string; code: string; title: string; headcount: number; budget_min?: number; budget_max?: number; status: string };
export default function RequisitionsPage() {
  const [items, setItems] = useState<Requisition[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { const result = await api<{ items: Requisition[] }>("/admin/requisitions"); setItems(result.items); } catch (err) { setError(err instanceof Error ? err.message : "Requisitions could not load"); } }
  useEffect(() => { load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = await api<{ message: string }>("/admin/requisitions", { method: "POST", body: JSON.stringify({ code: data.get("code"), title: data.get("title"), headcount: Number(data.get("headcount")), budget_min: Number(data.get("budget_min")) || null, budget_max: Number(data.get("budget_max")) || null, currency: data.get("currency"), justification: data.get("justification") }) }); setMessage(result.message); event.currentTarget.reset(); load(); } catch (err) { setError(err instanceof Error ? err.message : "Requisition could not be created"); } }
  async function decide(item: Requisition, status: "APPROVED" | "REJECTED") { try { const result = await api<{ message: string }>(`/admin/requisitions/${item.id}/decision`, { method: "PATCH", body: JSON.stringify({ status, comments: "" }) }); setMessage(result.message); load(); } catch (err) { setError(err instanceof Error ? err.message : "Decision failed"); } }
  return <div className="resource-page"><div className="container section"><Link className="back" href="/dashboard">← Dashboard</Link><span className="eyebrow">Workforce planning</span><h1>Hiring requisitions</h1>{message && <div className="notice success">{message}</div>}{error && <div className="notice error">{error}</div>}<div className="detail-grid"><section className="table-card"><h2>Requisitions</h2><table><thead><tr><th>Code</th><th>Role</th><th>Headcount</th><th>Budget</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.code}</td><td>{item.title}</td><td>{item.headcount}</td><td>{item.budget_min ?? "—"} - {item.budget_max ?? "—"}</td><td><span className="status">{item.status}</span></td><td>{item.status === "PENDING" && <><button className="button small" onClick={() => decide(item, "APPROVED")}>Approve</button> <button className="button small ghost" onClick={() => decide(item, "REJECTED")}>Reject</button></>}</td></tr>)}</tbody></table>{!items.length && <div className="notice">No requisitions.</div>}</section><form className="form-card" onSubmit={create}><h2>Create requisition</h2><label>Code<input name="code" required pattern="[A-Za-z0-9_-]+" /></label><label>Role title<input name="title" required /></label><label>Headcount<input name="headcount" type="number" min="1" defaultValue="1" required /></label><label>Minimum budget<input name="budget_min" type="number" min="0" /></label><label>Maximum budget<input name="budget_max" type="number" min="0" /></label><label>Currency<input name="currency" defaultValue="PKR" maxLength={3} required /></label><label>Justification<textarea name="justification" maxLength={5000} required /></label><button className="button full">Submit for approval</button></form></div></div></div>;
}