"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {api} from "@/lib/api";

type Metrics=Record<string,number|string|Record<string,number>>;
type User={id:string;full_name?:string;role:string;department?:string;job_title?:string};
type NavItem=[string,string];
const roleNavigation:Record<string,NavItem[]>={
 admin:[["Overview","/dashboard"],["Upcoming meetings","/dashboard/meetings"],["Applications","/dashboard/applications"],["Interviews","/dashboard/interviews"],["Hiring decisions","/dashboard/decisions"],["Offers","/dashboard/offers"],["Employees","/dashboard/employees"],["Jobs","/dashboard/jobs"],["Requisitions","/dashboard/requisitions"],["Users","/dashboard/users"],["Operations","/dashboard/operations"]],
 operator:[["Overview","/dashboard"],["Upcoming meetings","/dashboard/meetings"],["Applications","/dashboard/applications"],["Interviews","/dashboard/interviews"],["Offers","/dashboard/offers"],["Employees","/dashboard/employees"],["Jobs","/dashboard/jobs"],["Requisitions","/dashboard/requisitions"],["Operations","/dashboard/operations"]],
 hr:[["Overview","/dashboard"],["Upcoming meetings","/dashboard/meetings"],["Applications","/dashboard/applications"],["Interviews","/dashboard/interviews"],["Hiring decisions","/dashboard/decisions"],["Offers","/dashboard/offers"],["Employees","/dashboard/employees"],["Jobs","/dashboard/jobs"],["Requisitions","/dashboard/requisitions"]],
 recruiter:[["Overview","/dashboard"],["Upcoming meetings","/dashboard/meetings"],["Applications","/dashboard/applications"],["Interviews","/dashboard/interviews"],["Jobs","/dashboard/jobs"],["Requisitions","/dashboard/requisitions"]],
 hiring_manager:[["Overview","/dashboard"],["Upcoming meetings","/dashboard/meetings"],["Applications","/dashboard/applications"],["Interviews","/dashboard/interviews"],["Hiring decisions","/dashboard/decisions"],["Offers","/dashboard/offers"],["Requisitions","/dashboard/requisitions"]],
 interviewer:[["My interviews","/dashboard/interviews"],["Upcoming meetings","/dashboard/meetings"]]
};

export default function Dashboard(){
 const router=useRouter();
 const [user,setUser]=useState<User|null>(null),[metrics,setMetrics]=useState<Metrics>({}),[apps,setApps]=useState<any[]>([]),[interviews,setInterviews]=useState<any[]>([]),[error,setError]=useState("");
 useEffect(()=>{api<{user:User;requires_persona?:boolean}>("/auth/me").then(async result=>{if(result.requires_persona){router.replace("/staff-select");return}if(["candidate","employee"].includes(result.user.role)){router.replace("/portal");return}setUser(result.user);if(result.user.role==="interviewer"){const r=await api<{items:any[]}>("/admin/interviews");setInterviews(r.items)}else{const [m,a]=await Promise.all([api<{metrics:Metrics}>("/admin/dashboard"),api<{items:any[]}>("/admin/applications?page_size=10")]);setMetrics(m.metrics);setApps(a.items)}}).catch(reason=>setError(reason instanceof Error?reason.message:"Dashboard could not load"))},[router]);
 async function logout(){await api("/auth/logout",{method:"POST"});router.push("/login")}
 const nav=user?(roleNavigation[user.role]||[["Overview","/dashboard"]]):[];
 const cards:Array<[string,number]>=[["Applications",Number(metrics.applications_total)||0],["Today",Number(metrics.applications_today)||0],["Manual review",Number(metrics.manual_review_count)||0],["Pending interviews",Number(metrics.pending_interview_confirmations)||0],["Pending approvals",Number(metrics.pending_offer_approvals)||0],["Onboarding",Number(metrics.employees_onboarding)||0]];
 return <div className="dashboard"><aside className="dash-nav"><div className="brand light"><span className="brand-mark">N</span><span>NovaTech</span></div><nav>{nav.map(([label,href])=><Link className={href==="/dashboard"?"active":""} key={href} href={href}>{label}</Link>)}</nav><button onClick={logout}>Sign out</button></aside><section className="dash-main"><div className="dash-head"><div><span className="eyebrow">{user?.job_title||user?.role?.replaceAll("_"," ")||"Recruitment operations"}</span><h1>{user?.role==="interviewer"?"My interview workspace":"Hiring overview"}</h1></div><span className="health">● System healthy</span></div>{error&&<div className="notice error">{error}</div>}{user?.role==="interviewer"?<section className="table-card"><div className="table-head"><h2>Assigned interviews</h2><Link href="/dashboard/interviews">Open interview board →</Link></div><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Position</th><th>Schedule</th><th>Status</th><th>Action</th></tr></thead><tbody>{interviews.map(item=><tr key={item.id}><td>{item.applications?.name_at_application||"—"}</td><td>{item.applications?.job_positions?.title||"—"}</td><td>{item.scheduled_start?new Date(item.scheduled_start).toLocaleString():"Not scheduled"}</td><td><span className="status">{item.status}</span></td><td><Link href={`/dashboard/interviews/${item.id}`}>Open workspace</Link></td></tr>)}</tbody></table></div>{!interviews.length&&!error&&<div className="notice">No interviews are assigned to this profile.</div>}</section>:<><div className="metric-cards">{cards.map(([label,value])=><article key={label}><span>{label}</span><b>{value}</b></article>)}</div><section className="table-card"><div className="table-head"><h2>Recent applications</h2><Link href="/dashboard/applications">View all →</Link></div><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Position</th><th>Status</th><th>Score</th><th>Submitted</th></tr></thead><tbody>{apps.map(application=><tr key={application.id}><td><b>{application.name_at_application}</b><small>{application.email_at_application}</small></td><td>{application.job_positions?.title||"—"}</td><td><span className="status">{application.status}</span></td><td>{application.final_score??"—"}</td><td>{new Date(application.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>{!apps.length&&!error&&<div className="notice">No applications available.</div>}</section></>}</section></div>;
}
